# golangci-lint configuration for NTM
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - staticcheck

    # Additional linters
    - bodyclose
    - dogsled
    - durationcheck
    - gofmt
    - goimports
    - gosec
    - nakedret
    - nolintlint
    - rowserrcheck
    - sqlclosecheck

  disable:
    - funlen           # Function length - too strict for TUI code
    - gochecknoglobals # We use package-level vars for themes/config
    - lll              # Line length - TUI rendering often needs long lines
    - wsl              # Too strict about whitespace
    - gocognit         # Cognitive complexity - too strict for some complex functions
    - prealloc         # Pre-allocation hints - optimization, not correctness
    - unparam          # Unused parameters - often needed for interface compliance
    - exhaustive       # Switch exhaustiveness - not all cases need handling
    - unused           # Dead code detection - we have intentional unused code for future use
    - ineffassign      # Ineffectual assignments - too noisy
    - wastedassign     # Wasted assignments - too noisy
    - goconst          # String constants - too noisy
    - gocritic         # Too many style nits
    - gocyclo          # Cyclomatic complexity - too strict
    - godot            # Comment periods - stylistic
    - goprintffuncname # Printf naming conventions - not critical
    - misspell         # US vs UK spelling - not critical
    - noctx            # HTTP context - existing code predates this
    - revive           # Too many style rules
    - stylecheck       # Too many style rules
    - thelper          # Test helper hints - not critical
    - tparallel        # Test parallel hints - not critical
    - unconvert        # Unnecessary conversions - minor
    - whitespace       # Whitespace style - minor
    - dupl             # Duplicate code detection - too noisy
    - predeclared      # Naming conflicts with builtins - stylistic preference
    - gosimple         # Simplification suggestions - existing code works fine

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - (os.File).Close
      - (*os.File).Close

  govet:
    enable-all: true
    disable:
      - shadow         # Too many false positives
      - fieldalignment # Struct field ordering optimization - too noisy
      - unusedwrite    # Unused writes - often in tests for struct initialization

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/Dicklesworthstone/ntm

  gosec:
    excludes:
      - G104  # Unhandled errors - too noisy
      - G110  # Decompression bomb - we trust our inputs
      - G115  # Integer overflow - handled appropriately
      - G204  # Subprocess - we intentionally run commands
      - G301  # Directory permissions - appropriate for use case
      - G302  # File permissions - appropriate for use case
      - G304  # File path from variable - we intentionally do this
      - G305  # File traversal - handled appropriately
      - G306  # File permissions - appropriate for use case
      - G404  # Weak random - not used for security

  nakedret:
    max-func-lines: 50

issues:
  exclude-rules:
    # Exclude errcheck from test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - staticcheck

    # Exclude errcheck from CLI - many intentional unchecked errors for UX
    - path: internal/cli/
      linters:
        - errcheck

    # Exclude errcheck from specific packages with intentional unchecked errors
    - path: internal/(checkpoint|agentmail|cass|bv|auth|tmux|config|robot|events|history|notify|output|quota|tui|status|scanner|prompt)/
      linters:
        - errcheck

    # Exclude errcheck from tests directory
    - path: tests/
      linters:
        - errcheck

    # Exclude deprecated API warnings (SA1019) - we handle these appropriately
    - linters:
        - staticcheck
      text: "SA1019:"

    # Exclude empty branch warnings (SA9003) - intentional structure
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude return value ignored warnings (SA4017)
    - linters:
        - staticcheck
      text: "SA4017:"

    # Exclude nil pointer dereference warnings in tests (SA5011)
    - linters:
        - staticcheck
      text: "SA5011:"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: warning
  rules:
    - linters:
        - govet
      severity: error
